spring.application.name=eclm_service
server.servlet.context-path=/
server.port=8440
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:dodaso_keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-alias=dodaso-server

# Eureka Client configuration
#eureka.instance.lease-renewal-interval-in-seconds=3
eureka.client.service-url.defaultZone=https://localhost:9443/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Eureka HTTPS configuration
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=8443
eureka.instance.non-secure-port-enabled=false
eureka.instance.status-page-url=https://localhost:8443/actuator/info
eureka.instance.health-check-url=https://localhost:8443/actuator/health
eureka.instance.home-page-url=https://localhost:8443/
eureka.client.registry-fetch-interval-seconds=30
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

eureka.client.tls.enabled=true
eureka.client.tls.trust-store=classpath:dodaso_truststore.p12
eureka.client.tls.trust-store-password=changeit
eureka.client.tls.trust-store-type=PKCS12

#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:SSLKeystore-local.p12
#server.ssl.key-store-password=Dod@s0123
#server.ssl.key-alias=enterprise
#spring.application.name=spring-cloud-eureka-client
# Service Discovery
#eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
# Service Discovery with SSL
#eureka.client.service-url.defaultZone=${EUREKA_URI:https://localhost:9443/eureka}
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.prefer-ip-address=false
#eureka.instance.hostname=localhost
#eureka.instance.secure-port-enabled=true
#eureka.instance.secure-port=443
#eureka.instance.non-secure-port-enabled=false
#eureka.instance.lease-renewal-interval-in-seconds=5
#
## SSL Trust Store Configuration
#eureka.client.tls.enabled=true
#eureka.client.tls.trust-store=classpath:EurekaTruststore-local.p12
#eureka.client.tls.trust-store-password=Dod@s0123
#eureka.client.tls.trust-store-type=PKCS12

# Eureka Client configuration
#eureka.instance.lease-renewal-interval-in-seconds=3
#eureka.client.service-url.defaultZone=https://localhost:9443/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
## Eureka HTTPS configuration
#eureka.instance.secure-port-enabled=true
#eureka.instance.secure-port=443
#eureka.instance.non-secure-port-enabled=false
#eureka.instance.status-page-url=https://localhost:443/actuator/info
#eureka.instance.health-check-url=https://localhost:443/actuator/health
#eureka.instance.home-page-url=https://localhost:443/
#
#eureka.client.tls.enabled=true
#eureka.client.tls.trust-store=classpath:dodaso_truststore.p12
#eureka.client.tls.trust-store-password=changeit
#eureka.client.tls.trust-store-type=PKCS12

# Debug logging
#logging.level.com.netflix.discovery=ERROR
#logging.level.com.netflix.eureka=ERROR
#Turn Statistics on and log SQL stmts
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false
# Local only
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.jdbc.batch_size=10
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.hibernate.naming.physical-strategy=com.dodaso.ecosystem.baseline.common.PhysicalNamingStrategyImpl
spring.datasource.driverClassName=com.p6spy.engine.spy.P6SpyDriver
#spring.datasource.url=jdbc:p6spy:mysql://adevdb-lcws.cftzmcxembgz.us-east-1.rds.amazonaws.com:3306/ecws?createDatabaseIfNotExist=true&rewriteBatchedStatements=true&useSSL=false
spring.datasource.url=jdbc:p6spy:mysql://adev.mysql.database.azure.com:3306/ecws?createDatabaseIfNotExist=true&rewriteBatchedStatements=true&useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=admin
#spring.datasource.password=reqrIyT7ReA54YsjKi5z
#spring.datasource.username=root
#spring.datasource.password=ENC(KDB6uneNotJkVJz3xCoeZA==)
spring.datasource.username=developer
spring.datasource.password=ENC(4A1aNWphG1Rf6mCCr5DAtiVidLpC8IpRLsrZxY3zfMZbnyAVXb/6Fg==)
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator
#pwd123
#spring.datasource.username=ENC(y8mr7cgKJ4Nh8c9MOwPur8Im8jDWIKFAw3QgrNgxgPNr4PbaLzXcIkARHGKBUkJb)
#spring.datasource.password=ENC(lINf7kj7cXDPca6ibREgtSVxnb+9HVQaEzXiyoaIZbI72TQjxGcWkdDH/ZSPXWG+CDmOaUHrVtwAaXtE+2CT+Q==)
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
#HikariCP Settings
#Default auto commit of Hikari is true
#spring.datasource.hikari.auto-commit: true
#spring.datasource.hikari.minimumIdle=10
#spring.datasource.hikari.maximumPoolSize=20
#spring.datasource.hikari.idleTimeout=30000N
spring.datasource.hikari.poolName=ecws-service-hikariCP
# 10 minutes
spring.datasource.hikari.maxLifetime=600000
#TODO: once we purchase a certificate from azure, we should test out https instead of http.
#azure.blob.storage.connection=DefaultEndpointsProtocol=http;AccountName=adevblobstorageuser;AccountKey=UVsiusWqSkA5zV8I3ZbmMxF+yYhTyzfYrE21ogNcSadMpGmFuQU8K4M7QVf0CGY/3jP1Z9GmNnEs+AStg84mpQ==;EndpointSuffix=core.windows.net
#azure.blob.storage.endpoint=http://adevblobstorageuser.blob.core.windows.net/
#azure.blob.storage.token=sv=2024-11-04&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2025-12-31T05:30:48Z&st=2025-04-07T20:30:48Z&spr=https,http&sig=s9WrEfnGoZeuvUXOY2F8tq5WJO%2FrAhlLyzlA%2Bh2mlJU%3D
azure.storage.account-name=adevblobstorageuser
azure.storage.account-key=UVsiusWqSkA5zV8I3ZbmMxF+yYhTyzfYrE21ogNcSadMpGmFuQU8K4M7QVf0CGY/3jP1Z9GmNnEs+AStg84mpQ==
# Local only
logging.level.org.hibernate.stat=info
auth.jwt.header=Authorization
auth.jwt.expiration=30000000
auth.jwt.secret=9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9

dashboard.insights.metrics.limit=100

dep.wf.defaultType=FINISH_TO_START
dep.wf.enableParent=true
dep.wf.enableSiblingChain=true
dep.wf.minGroupSize=2

# Enable/disable the scheduler
ecws.scheduler.ctd.enabled=true

# Cron (default is every hour if not set)
ecws.scheduler.ctd.cron=0 0 * * * *